### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Gdiazdiaz**
## Tasks completed

- Add endpoints for random greeting.

### CODE REVIEW

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @Gdiazdiaz,

### Nice job, you are almost there.

cat-driving-serious

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the required suggestion I left in the [front-end PR.](https://github.com/Gdiazdiaz/Hello-Frontend/pull/1#pullrequestreview-1412135715)
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_two_apps.md#:~:text=database%20set%20up.-,Create%20a%20table%20for%20storing%20your%20messages%20and%20create%205%20different%20greetings.,-Create%20an%20API), Please make the endpoint return a random greeting from a created list of greetings because the API endpoint you created is returning `null`.

image


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Gdiazdiaz** [comment]
Hey @Omar-Muhamad did you populate the database? Returning nul mean the database is empty

**Comment by omar-muhamad** [comment]
> Hey @Omar-Muhamad did you populate the database? Returning nul mean the database is empty

As per this [requirement ](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_two_apps.md#:~:text=and%20create%205%20different%20greetings.) kindly you suppose to do that. not me.
[Hint] You can add seeds.

**Review by andersonlebon — APPROVED** [review]
## Hi @Gdiazdiaz 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

nodding-yes


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
